version: '3'

services:

  card-statement-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=card-statement
      - MYSQL_USER=card-statement-user
      - MYSQL_PASSWORD=password
    ports:
      - 3308:3306

#  transaction:
#    image: zupacademy/card-statement
#    restart: on-failure
#    depends_on:
#      - card-statement-mysql
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_HOST=card-statement-mysql
#      - DATABASE_USER=card-statement-user
#      - DATABASE_PASSWORD=password
#      - DATABASE_NAME=cardStatement
#      - DATABASE_PORT=3307
